skip what-if step temporaly

diff --git a/.github/workflows/5.internal-document-search-deploy.yml b/.github/workflows/5.internal-document-search-deploy.yml
--- a/.github/workflows/5.internal-document-search-deploy.yml
+++ b/.github/workflows/5.internal-document-search-deploy.yml
@@ -15,16 +15,14 @@ jobs:
           creds: ${{ secrets.AZURE_CREDENTIALS }} 
           enable-AzPSSession: true
       
-      - name: what-if using Azure CLI
-        run: |
-          # results=$(az deployment sub what-if --template-file "./5.internal-document-search/infra/main.bicep" --location JapanEast -p vmLoginPassword=dummy -p resourceGroupName=rg-${{ github.run_id }} -p isPrivateNetworkEnabled=false -p environmentName=${{ github.run_id }} -p location=japaneast)
-          $results = az deployment sub what-if --template-file "./5.internal-document-search/infra/main.bicep" --location JapanEast -p vmLoginPassword=dummy -p resourceGroupName=rg-${{ github.run_id }} -p isPrivateNetworkEnabled=false -p environmentName=${{ github.run_id }} -p location=japaneast
-          echo "Result: $results"
-          # Check if "Error" is present in $results
-          if echo "$results" | grep -i "Error"; then
-            echo "Error found in what-if results. Exiting..."
-            exit 1
-          fi
+      # - name: what-if using Azure CLI
+      #   run: |
+      #     results=$(az deployment sub what-if --template-file "./5.internal-document-search/infra/main.bicep" --location JapanEast -p vmLoginPassword=dummy -p resourceGroupName=rg-${{ github.run_id }} -p isPrivateNetworkEnabled=false -p environmentName=${{ github.run_id }} -p location=japaneast)          echo "Result: $results"
+      #     # Check if "Error" is present in $results
+      #     if echo "$results" | grep -i "Error"; then
+      #       echo "Error found in what-if results. Exiting..."
+      #       exit 1
+      #     fi
       
       - name: Deploy Azure Resources
         uses: azure/powershell@v1
