Add Delete Azure Resources

diff --git a/.github/workflows/5.internal-document-search-deploy.yml b/.github/workflows/5.internal-document-search-deploy.yml
--- a/.github/workflows/5.internal-document-search-deploy.yml
+++ b/.github/workflows/5.internal-document-search-deploy.yml
@@ -31,9 +31,10 @@ jobs:
             $ENV:STORAGE_ACCOUNT_NAME = "st${{ github.run_id }}"
             $ENV:SEARCH_SERVICE_NAME = "gptkb-${{ github.run_id }}"
             $ENV:FORMRECOGNIZER_SERVICE_NAME = "cog-fr-${{ github.run_id }}"
+            $ENV:COGNITIVE_SERVICES_NAME = "cog-${{ github.run_id }}"
 
             cd 5.internal-document-search/infra
-            $results = az deployment sub create --name $ENV:DEP_NAME --location $ENV:LOC --template-file main.bicep --parameters principalId=$ENV:AZURE_PRINCIPAL_ID environmentName=$ENV:AZURE_ENV_NAME location=$ENV:LOC backendServiceName=$ENV:BACKEND_SERVICE_NAME appServicePlanName=$ENV:APP_SERVICE_PLAN_NAME storageAccountName=$ENV:STORAGE_ACCOUNT_NAME searchServiceName=$ENV:SEARCH_SERVICE_NAME formRecognizerServiceName=$ENV:FORMRECOGNIZER_SERVICE_NAME vmLoginPassword=dummy isPrivateNetworkEnabled=false
+            $results = az deployment sub create --name $ENV:DEP_NAME --location $ENV:LOC --template-file main.bicep --parameters principalId=$ENV:AZURE_PRINCIPAL_ID environmentName=$ENV:AZURE_ENV_NAME location=$ENV:LOC backendServiceName=$ENV:BACKEND_SERVICE_NAME appServicePlanName=$ENV:APP_SERVICE_PLAN_NAME storageAccountName=$ENV:STORAGE_ACCOUNT_NAME searchServiceName=$ENV:SEARCH_SERVICE_NAME formRecognizerServiceName=$ENV:FORMRECOGNIZER_SERVICE_NAME openAiServiceName=$ENV:COGNITIVE_SERVICES_NAME vmLoginPassword=dummy isPrivateNetworkEnabled=false
             
             echo "$results"
 
@@ -66,7 +67,14 @@ jobs:
             $ENV:WEBAPP_NAME = "app-backend-${{ github.run_id }}"
 
             cd 5.internal-document-search/src/backend
-            az webapp deployment source config-zip --resource-group $ENV:AZURE_WEBAPP_RESOURCE_GROUP --name $ENV:WEBAPP_NAME --src ./app.zip
+            $results = az webapp deployment source config-zip --resource-group $ENV:AZURE_WEBAPP_RESOURCE_GROUP --name $ENV:WEBAPP_NAME --src ./app.zip
+            
+            echo "$results"
+
+            if ($results -contains "ERROR") {
+              echo "Deployment failed"
+              exit 1
+            }
           azPSVersion: "latest"
       
       - name: Assgin RBAC to CosmosDB
@@ -136,4 +144,18 @@ jobs:
 
             $cwd = (Get-Location)
             Start-Process -FilePath $venvPythonPath -ArgumentList "./scripts/prepdocs.py $cwd/data/* --storageaccount $env:AZURE_STORAGE_ACCOUNT --container $env:AZURE_STORAGE_CONTAINER --storagekey $env:AZURE_STORAGE_KEY --searchservice $env:AZURE_SEARCH_SERVICE --searchkey $env:AZURE_SEARCH_KEY --index $env:AZURE_SEARCH_INDEX --formrecognizerservice $env:AZURE_FORMRECOGNIZER_SERVICE --formrecognizerkey $env:AZURE_FORMRECOGNIZER_KEY -v --managedidentitycredential" -Wait -NoNewWindow
+          azPSVersion: "latest"
+
+      - name: Delete Azure Resources
+        uses: azure/powershell@v1
+        with:
+          inlineScript: |
+            $ENV:RESOURCE_GROUP_NAME = "rg-github-actions-test-${{ github.run_id }}"
+            $ENV:SUB = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+            $ENV:LOC = "${{ secrets.AZURE_LOCATION }}"
+            $ENV:COGNITIVE_SERVICES_NAME = "cog-${{ github.run_id }}"
+
+            cd 5.internal-document-search/infra
+            az deployment sub delete --name $ENV:DEP_NAME --yes
+            az resource delete --ids /subscriptions/$ENV:SUB/providers/Microsoft.CognitiveServices/locations/$ENV:LOC/resourceGroups/$ENV:RESOURCE_GROUP_NAME/deletedAccounts/$ENV:COGNITIVE_SERVICES_NAME
           azPSVersion: "latest"
